// This catalog mirrors the Rust trainer so both examples expose the same choices.
const HORSES = [
    ["American Paint - Overo", "a_c_horse_americanpaint_overo"],
    ["American Paint - Tobiano", "a_c_horse_americanpaint_tobiano"],
    ["Appaloosa - Blanket", "a_c_horse_appaloosa_blanket"],
    ["Appaloosa - Leopard", "a_c_horse_appaloosa_leopard"],
    ["Arabian - Black", "a_c_horse_arabian_black"],
    ["Arabian - White", "a_c_horse_arabian_white"],
    ["Ardennes - Bay Roan", "a_c_horse_ardennes_bayroan"],
    ["Ardennes - Iron Grey", "a_c_horse_ardennes_irongreyroan"],
    ["Belgian - Blond Chestnut", "a_c_horse_belgian_blondchestnut"],
    ["Belgian - Mealy Chestnut", "a_c_horse_belgian_mealychestnut"],
    ["Gang Horse - Arthur", "a_c_horse_gang_arthur"],
    ["Gang Horse - Bill", "a_c_horse_gang_bill"],
    ["Gang Horse - Charles", "a_c_horse_gang_charles"],
    ["Gang Horse - Dutch", "a_c_horse_gang_dutch"],
    ["Gang Horse - Hosea", "a_c_horse_gang_hosea"],
    ["Gang Horse - Javier", "a_c_horse_gang_javier"],
    ["Gang Horse - John", "a_c_horse_gang_john"],
    ["Gang Horse - Lenny", "a_c_horse_gang_lenny"],
    ["Gang Horse - Micah", "a_c_horse_gang_micah"],
    ["Gang Horse - Sadie", "a_c_horse_gang_sadie"],
    ["Gang Horse - Sean", "a_c_horse_gang_sean"],
    ["Gang Horse - Trelawny", "a_c_horse_gang_trelawney"],
    ["Missouri Fox Trotter", "a_c_horse_missourifoxtrotter_silverdapplepinto"],
    ["Mustang - Wild Bay", "a_c_horse_mustang_wildbay"],
    ["Nokota - Blue Roan", "a_c_horse_nokota_blueroan"],
    ["Shire - Raven Black", "a_c_horse_shire_ravenblack"],
    ["Thoroughbred - Dapple Grey", "a_c_horse_thoroughbred_dapplegrey"],
    ["Turkoman - Albino", "a_c_horse_turkoman_albino"],
    ["Turkoman - Gold", "a_c_horse_turkoman_gold"],
    ["Winter Horse", "a_c_horse_winter02_01"],
];

const CHARACTERS = [
    ["Arthur Morgan", "player_zero"],
    ["John Marston", "player_three"],
    ["Dutch van der Linde", "cs_dutch"],
    ["Hosea Matthews", "cs_hoseamatthews"],
    ["Micah Bell", "cs_micahbell"],
    ["Sadie Adler", "cs_mrsadler"],
    ["Abigail Roberts", "cs_abigailroberts"],
    ["Charles Smith", "cs_charlessmith"],
    ["Bill Williamson", "cs_billwilliamson"],
    ["Javier Escuella", "cs_javierescuella"],
    ["Lenny Summers", "cs_lenny"],
    ["Sean MacGuire", "cs_sean"],
    ["Uncle", "cs_uncle"],
    ["Jack Marston", "cs_jackmarston"],
    ["Angelo Bronte", "cs_bronte"],
    ["Colm O'Driscoll", "cs_colmodriscoll"],
    ["Leviticus Cornwall", "cs_leviticuscornwall"],
    ["Edgar Ross", "cs_edgarross"],
    ["Andrew Milton", "cs_miltonandrews"],
    ["Valentine Deputy", "s_m_m_valdeputy_01"],
    ["Saint Denis Police", "s_m_m_ambientsdpolice_01"],
    ["Rhodes Cowpoke", "s_m_m_rhdcowpoke_01"],
    ["Valentine Cowpoke", "s_m_m_valcowpoke_01"],
    ["Train Station Worker", "s_m_m_trainstationworker_01"],
];

const VEHICLES = [
    ["Canoe", "canoe"],
    ["Tree Trunk Canoe", "canoeTreeTrunk"],
    ["Rowboat", "rowboat"],
    ["Swamp Rowboat", "rowboatSwamp"],
    ["Pirogue", "pirogue"],
    ["Keelboat", "keelboat"],
    ["Steam Boat", "boatSteam02x"],
    ["Cart 01", "cart01"],
    ["Cart 02", "cart02"],
    ["Cart 03", "cart03"],
    ["Cart 04", "cart04"],
    ["Cart 05", "cart05"],
    ["Cart 06", "cart06"],
    ["Cart 07", "cart07"],
    ["Cart 08", "cart08"],
    ["Coach 2", "coach2"],
    ["Coach 3", "coach3"],
    ["Coach 4", "coach4"],
    ["Coach 5", "coach5"],
    ["Coach 6", "coach6"],
    ["Buggy 01", "buggy01"],
    ["Buggy 02", "buggy02"],
    ["Buggy 03", "buggy03"],
    ["Army Supply Wagon", "ArmySupplyWagon"],
    ["Chuck Wagon", "chuckwagon000x"],
    ["Supply Wagon", "supplywagon"],
    ["Supply Wagon 2", "supplywagon2"],
    ["Log Wagon", "logwagon"],
    ["Log Wagon 2", "logwagon2"],
    ["Coal Wagon", "coal_wagon"],
    ["Gatling Gun", "gatling_gun"],
    ["Gatling Maxim", "gatlingMaxim02"],
    ["Handcart", "handcart"],
    ["Horse Boat", "horseBoat"],
    ["Hot Air Balloon", "hotAirBalloon01"],
    ["Hotchkiss Cannon", "hotchkiss_cannon"],
    ["Police Wagon", "policeWagon01x"],
    ["Police Gatling Wagon", "policeWagongatling01x"],
    ["Oil Wagon 01", "oilWagon01x"],
    ["Oil Wagon 02", "oilWagon02x"],
    ["Stagecoach 001", "stagecoach001x"],
    ["Stagecoach 002", "stagecoach002x"],
    ["Stagecoach 003", "stagecoach003x"],
    ["Stagecoach 004", "stagecoach004x"],
    ["Stagecoach 005", "stagecoach005x"],
    ["Stagecoach 006", "stagecoach006x"],
    ["Trolley", "trolley01x"],
    ["Wagon 02", "wagon02x"],
    ["Wagon 03", "wagon03x"],
    ["Wagon 04", "wagon04x"],
    ["Wagon 05", "wagon05x"],
    ["Wagon 06", "wagon06x"],
    ["Circus Wagon 01", "wagonCircus01x"],
    ["Circus Wagon 02", "wagonCircus02x"],
    ["Doctor Wagon", "wagonDoc01x"],
    ["Prison Wagon", "wagonPrison01x"],
    ["Work Wagon", "wagonWork01x"],
    ["Dairy Wagon", "wagonDairy01x"],
    ["Traveller Wagon", "wagonTraveller01x"],
    ["Armored Car", "armoredCar01x"],
    ["Breach Cannon", "breach_cannon"],
    ["Private Passenger Car", "privatepassenger01x"],
    ["Private Dining Car", "privateDining01x"],
    ["Private Steamer", "privateSteamer01x"],
    ["North Steamer", "northSteamer01x"],
    ["Ghost Train Steamer", "GhostTrainSteamer"],
    ["Ghost Train Passenger", "GhostTrainPassenger"],
    ["Private Sleeper 02", "privateopensleeper02x"],
    ["Private Sleeper 01", "privateopensleeper01x"],
    ["Dummy Steamer", "steamerDummy"],
    ["Armored Car 03", "armoredCar03x"],
    ["Private Baggage Car", "privatebaggage01x"],
    ["Smuggler Boat", "smuggler02"],
    ["Refrigerator Car", "midlandrefrigeratorCar"],
    ["Midland Boxcar", "midlandboxcar05x"],
    ["Caboose", "caboose01x"],
    ["Cutscene Coach", "coach3_cutscene"],
    ["Chuck Wagon 002", "chuckwagon002x"],
    ["Mine Cart", "mineCart01x"],
    ["North Flatcar", "northflatcar01x"],
    ["Private Flatcar", "privateflatcar01x"],
    ["North Passenger 01", "northpassenger01x"],
    ["North Passenger 03", "northpassenger03x"],
    ["Pirogue 2", "pirogue2"],
    ["Private Coal Car", "privateCoalCar01x"],
    ["North Coal Car", "NorthCoalCar01x"],
    ["Winter Steamer", "winterSteamer"],
    ["Winter Coal Car", "wintercoalcar"],
    ["Private Boxcar 04", "privateboxcar04x"],
    ["Private Boxcar 02", "privateboxcar02x"],
    ["Private Boxcar 01", "privateboxcar01x"],
    ["Coal Hopper", "coalHopper01x"],
    ["Private Observation Car", "privateObservationcar"],
    ["Private Armoured Car", "privateArmoured"],
    ["Private Rooms Car", "privateRooms01x"],
    ["Ghost Train Coal Car", "GhostTrainCoalCar"],
    ["Ghost Train Caboose", "GhostTrainCaboose"],
    ["RC Boat", "rcBoat"],
    ["Swamp Rowboat 02", "rowboatSwamp02"],
    ["Guarma Ship", "ship_guama02"],
    ["Turbine Boat", "turbineboat"],
    ["NBD Guarma Ship", "ship_nbdGuama"],
    ["NBD Guarma Ship 2", "ship_nbdGuama2"],
    ["Skiff", "skiff"],
    ["Tugboat 2", "TugBoat2"],
    ["Utility Wagon", "utilliwag"],
    ["Gatling Chuck Wagon", "gatchuck"],
    ["Gatling Chuck Wagon 2", "gatchuck_2"],
];

const TELEPORTS = [
    ["Saint Denis", 2700.1, -1403.39, 46.6373],
    ["Van Horn", 2962.82, 583.162, 44.2948],
    ["Annesburg", 2941.17, 1358.08, 44.0665],
    ["Maclean's House", 2252.3, -135.647, 46.2262],
    ["Hagen Orchards", 2069.06, -861.575, 42.4468],
    ["Caliga Hall", 1797.61, -1352.64, 43.8385],
    ["Braithwaite Manor", 889.869, -1910.26, 45.2703],
    ["Emerald Ranch", 1424.09, 316.904, 88.6065],
    ["Scarlett Meadows", 1211.79, -201.815, 101.436],
    ["Alone Tree", 491.451, -307.623, 143.75],
    ["Flatneck Station", -344.127, -363.465, 88.0377],
    ["Wallace Station", -1308.38, 400.834, 95.3829],
    ["Riggs Station", -1087.97, -585.786, 81.4831],
    ["Valentine", -262.849, 793.404, 118.587],
    ["Chadwick Farm", -391.389, 916.105, 117.644],
    ["Fort Wallace", 366.483, 1456.73, 178.916],
    ["Downes Ranch", -822.636, 325.741, 95.2731],
    ["Strawberry", -1815.63, -396.749, 161.602],
    ["Big Valley", -1819.9, -599.968, 154.616],
    ["Holding Camp", -1588.19, -936.054, 84.1072],
    ["Blackwater", -858.065, -1337.73, 44.4866],
    ["Great Plains", -898.997, -1654.69, 68.5928],
    ["Quaker's Cove", -1191.3, -1950.71, 43.5789],
    ["Thieves Landing", -1452.17, -2329.4, 42.9603],
];

const WEATHER = [
    "OVERCAST", "RAIN", "FOG", "SNOWLIGHT", "THUNDER", "BLIZZARD", "SNOW",
    "MISTY", "SUNNY", "HIGHPRESSURE", "CLEARING", "SLEET", "DRIZZLE",
    "SHOWER", "SNOWCLEARING", "OVERCASTDARK", "THUNDERSTORM", "SANDSTORM",
    "HURRICANE", "HAIL", "WHITEOUT", "GROUNDBLIZZARD",
];
