# Bun's WebKit fork - JavaScriptCore prebuilt binaries
# Version: autobuild-cc5e0bddf7eae1d820cf673158845fe9bd83c094

set(BUN_WEBKIT_VERSION "autobuild-cc5e0bddf7eae1d820cf673158845fe9bd83c094")
set(BUN_WEBKIT_BASE_URL "https://github.com/oven-sh/webkit/releases/download/${BUN_WEBKIT_VERSION}")

# Only support x64 Windows for now
vcpkg_check_linkage(ONLY_STATIC_LIBRARY)

if(NOT VCPKG_TARGET_IS_WINDOWS OR NOT VCPKG_TARGET_ARCHITECTURE STREQUAL "x64")
    message(FATAL_ERROR "This port currently only supports x64-windows")
endif()

# Download release build
vcpkg_download_distfile(ARCHIVE_RELEASE
    URLS "${BUN_WEBKIT_BASE_URL}/bun-webkit-windows-amd64.tar.gz"
    FILENAME "bun-webkit-windows-amd64-${BUN_WEBKIT_VERSION}.tar.gz"
    SHA512 68537193628003fd21a1dd84683e49b050819c290cc547c7dac556b6c11760109f046ea063a84fb2d2c72d18c4944413b64e0b6bc70493c199b2b76046891a13
)

# Download debug build
vcpkg_download_distfile(ARCHIVE_DEBUG
    URLS "${BUN_WEBKIT_BASE_URL}/bun-webkit-windows-amd64-debug.tar.gz"
    FILENAME "bun-webkit-windows-amd64-debug-${BUN_WEBKIT_VERSION}.tar.gz"
    SHA512 8210c8438d6e8e3563dd779b461aa310233666ba794682c75a05a80dc0a2bf37ba62df59cf60d40b8149dd81a784da01b8edf74c1e77454f0d52167f2e794f19
)

# Extract release archive
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH_RELEASE
    ARCHIVE "${ARCHIVE_RELEASE}"
    NO_REMOVE_ONE_LEVEL
)

# Extract debug archive
vcpkg_extract_source_archive_ex(
    OUT_SOURCE_PATH SOURCE_PATH_DEBUG
    ARCHIVE "${ARCHIVE_DEBUG}"
    NO_REMOVE_ONE_LEVEL
)

# Install headers (from release build)
file(INSTALL "${SOURCE_PATH_RELEASE}/bun-webkit/include/"
    DESTINATION "${CURRENT_PACKAGES_DIR}/include"
    FILES_MATCHING
    PATTERN "*.h"
    PATTERN "*.hpp"
)

# Install release libraries
file(INSTALL "${SOURCE_PATH_RELEASE}/bun-webkit/lib/"
    DESTINATION "${CURRENT_PACKAGES_DIR}/lib"
    FILES_MATCHING PATTERN "*.lib"
)

# Install debug libraries
file(INSTALL "${SOURCE_PATH_DEBUG}/bun-webkit/lib/"
    DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib"
    FILES_MATCHING PATTERN "*.lib"
)

# Install release binaries
file(INSTALL "${SOURCE_PATH_RELEASE}/bun-webkit/bin/"
    DESTINATION "${CURRENT_PACKAGES_DIR}/bin"
    FILES_MATCHING
    PATTERN "*.exe"
    PATTERN "*.dll"
)

# Install debug binaries and symbols
file(INSTALL "${SOURCE_PATH_DEBUG}/bun-webkit/bin/"
    DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin"
    FILES_MATCHING
    PATTERN "*.exe"
    PATTERN "*.dll"
    PATTERN "*.pdb"
)

# Install additional files
file(INSTALL "${SOURCE_PATH_RELEASE}/bun-webkit/CombinedDomains.json"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)

# Install usage file
file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/usage"
    DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"
)

# Copy tools to tools/ directory instead of bin/
vcpkg_copy_tools(
    TOOL_NAMES jsc LLIntOffsetsExtractor LLIntSettingsExtractor
    AUTO_CLEAN
)

# Remove empty directories
file(REMOVE_RECURSE
    "${CURRENT_PACKAGES_DIR}/include/JavaScriptCore/inspector/remote"
    "${CURRENT_PACKAGES_DIR}/include/JavaScriptCore/unified-sources"
)

# Create a minimal copyright file
file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/copyright"
    "Bun's WebKit fork - JavaScriptCore\n"
    "Source: https://github.com/oven-sh/webkit\n"
    "Version: ${BUN_WEBKIT_VERSION}\n"
    "\n"
    "WebKit is licensed under BSD and LGPL licenses.\n"
    "See https://github.com/oven-sh/webkit for full license details.\n"
)

# Configure CMake targets
file(WRITE "${CURRENT_PACKAGES_DIR}/share/${PORT}/JavaScriptCoreConfig.cmake"
[=[
# Compute the installation prefix relative to this file
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# JavaScriptCore main library
add_library(JavaScriptCore::JavaScriptCore STATIC IMPORTED)
set_target_properties(JavaScriptCore::JavaScriptCore PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/JavaScriptCore.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/JavaScriptCore.lib"
    INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
    
    INTERFACE_COMPILE_DEFINITIONS "ALLOW_LINE_AND_COLUMN_NUMBER_IN_BUILTINS=1;BUN_SKIP_FAILING_ASSERTIONS=1;BUSE_TZONE=0;ENABLE_ACCESSIBILITY_ISOLATED_TREE=0;ENABLE_API_TESTS=0;ENABLE_APPLE_PAY=0;ENABLE_APPLICATION_MANIFEST=0;ENABLE_ASYNC_SCROLLING=0;ENABLE_ATTACHMENT_ELEMENT=0;ENABLE_AUTOCAPITALIZE=0;ENABLE_AVF_CAPTIONS=0;ENABLE_BREAKPAD=0;ENABLE_BUBBLEWRAP_SANDBOX=0;ENABLE_BUN_SKIP_FAILING_ASSERTIONS=1;ENABLE_CACHE_PARTITIONING=0;ENABLE_CONTENT_EXTENSIONS=0;ENABLE_CONTENT_FILTERING=0;ENABLE_CONTEXT_MENUS=1;ENABLE_CURSOR_VISIBILITY=0;ENABLE_C_LOOP=0;ENABLE_DARK_MODE_CSS=0;ENABLE_DATACUE_VALUE=0;ENABLE_DEVICE_ORIENTATION=0;ENABLE_DFG_JIT=1;ENABLE_DRAG_SUPPORT=0;ENABLE_ENCRYPTED_MEDIA=0;ENABLE_EXPERIMENTAL_FEATURES=0;ENABLE_EXPERIMENTAL_FEATURES=0;ENABLE_FTL_JIT=1;ENABLE_FTPDIR=1;ENABLE_FULLSCREEN_API=1;ENABLE_GAMEPAD=0;ENABLE_GEOLOCATION=1;ENABLE_GPU_PROCESS=0;ENABLE_IMAGE_DIFF=1;ENABLE_INSPECTOR_ALTERNATE_DISPATCHERS=1;ENABLE_INSPECTOR_ALTERNATE_DISPATCHERS=1;ENABLE_INSPECTOR_EXTENSIONS=0;ENABLE_INSPECTOR_TELEMETRY=0;ENABLE_IOS_GESTURE_EVENTS=0;ENABLE_IOS_TOUCH_EVENTS=0;ENABLE_JAVASCRIPT_SHELL=1;ENABLE_JIT=1;ENABLE_JSC_GLIB_API=0;ENABLE_LAYOUT_TESTS=0;ENABLE_LEGACY_CUSTOM_PROTOCOL_MANAGER=0;ENABLE_LEGACY_ENCRYPTED_MEDIA=0;ENABLE_LLVM_PROFILE_GENERATION=0;ENABLE_MALLOC_HEAP_BREAKDOWN=0;ENABLE_MALLOC_HEAP_BREAKDOWN=0;ENABLE_MATHML=1;ENABLE_MEDIA_CAPTURE=0;ENABLE_MEDIA_CONTROLS_CONTEXT_MENUS=0;ENABLE_MEDIA_RECORDER=0;ENABLE_MEDIA_SESSION=0;ENABLE_MEDIA_SESSION_COORDINATOR=0;ENABLE_MEDIA_SESSION_PLAYLIST=0;ENABLE_MEDIA_SOURCE=0;ENABLE_MEDIA_STATISTICS=0;ENABLE_MEDIA_STREAM=0;ENABLE_MEMORY_SAMPLER=0;ENABLE_MHTML=0;ENABLE_MINIBROWSER=0;ENABLE_MOUSE_CURSOR_SCALE=0;ENABLE_NAVIGATOR_STANDALONE=0;ENABLE_NOTIFICATIONS=1;ENABLE_OFFSCREEN_CANVAS=0;ENABLE_OFFSCREEN_CANVAS_IN_WORKERS=0;ENABLE_ORIENTATION_EVENTS=0;ENABLE_PAYMENT_REQUEST=0;ENABLE_PDFJS=0;ENABLE_PDFKIT_PLUGIN=0;ENABLE_PERIODIC_MEMORY_MONITOR=0;ENABLE_PICTURE_IN_PICTURE_API=0;ENABLE_POINTER_LOCK=0;ENABLE_REFTRACKER=0;ENABLE_RELEASE_LOG=0;ENABLE_REMOTE_INSPECTOR=1;ENABLE_REMOTE_INSPECTOR=1;ENABLE_RESOURCE_USAGE=1;ENABLE_RESOURCE_USAGE=1;ENABLE_SAMPLING_PROFILER=1;ENABLE_SANDBOX_EXTENSIONS=0;ENABLE_SERVICE_CONTROLS=0;ENABLE_SHAREABLE_RESOURCE=0;ENABLE_SMOOTH_SCROLLING=1;ENABLE_SPEECH_SYNTHESIS=0;ENABLE_SPELLCHECK=0;ENABLE_STATIC_JSC=1;ENABLE_SWIFT_DEMO_URI_SCHEME=0;ENABLE_TELEPHONE_NUMBER_DETECTION=0;ENABLE_TEXT_AUTOSIZING=0;ENABLE_THUNDER=0;ENABLE_TOUCH_EVENTS=0;ENABLE_UNIFIED_BUILDS=1;ENABLE_USER_MESSAGE_HANDLERS=1;ENABLE_VARIATION_FONTS=0;ENABLE_VIDEO=1;ENABLE_VIDEO_PRESENTATION_MODE=0;ENABLE_VIDEO_USES_ELEMENT_FULLSCREEN=1;ENABLE_WEBASSEMBLY=1;ENABLE_WEBASSEMBLY_BBQJIT=1;ENABLE_WEBASSEMBLY_OMGJIT=1;ENABLE_WEBDRIVER=0;ENABLE_WEBDRIVER_BIDI=0;ENABLE_WEBDRIVER_KEYBOARD_GRAPHEME_CLUSTERS=0;ENABLE_WEBDRIVER_KEYBOARD_INTERACTIONS=0;ENABLE_WEBDRIVER_MOUSE_INTERACTIONS=0;ENABLE_WEBDRIVER_TOUCH_INTERACTIONS=0;ENABLE_WEBDRIVER_WHEEL_INTERACTIONS=0;ENABLE_WEBGL=0;ENABLE_WEBGPU=0;ENABLE_WEBKIT_OVERFLOW_SCROLLING_CSS_PROPERTY=0;ENABLE_WEBXR=0;ENABLE_WEBXR_HIT_TEST=0;ENABLE_WEBXR_LAYERS=0;ENABLE_WEB_API_STATISTICS=0;ENABLE_WEB_AUDIO=1;ENABLE_WEB_AUTHN=0;ENABLE_WEB_CODECS=0;ENABLE_WEB_RTC=0;ENABLE_WIRELESS_PLAYBACK_TARGET=0;ENABLE_WK_WEB_EXTENSIONS=0;ENABLE_XSLT=1;HAVE_ALIGNED_MALLOC=1;HAVE_ERRNO_H=1;HAVE_FEATURES_H=0;HAVE_INT128_T=1;HAVE_LANGINFO_H=0;HAVE_LINUX_MEMFD_H=0;HAVE_LOCALTIME_R=0;HAVE_MALLOC_TRIM=0;HAVE_MAP_ALIGNED=0;HAVE_MMAP=0;HAVE_PTHREAD_MAIN_NP=0;HAVE_PTHREAD_NP_H=0;HAVE_REGEX_H=0;HAVE_SHM_ANON=0;HAVE_SIGNAL_H=0;HAVE_STATX=0;HAVE_STAT_BIRTHTIME=0;HAVE_SYS_PARAM_H=0;HAVE_SYS_TIMEB_H=1;HAVE_SYS_TIME_H=0;HAVE_TIMEGM=0;HAVE_TIMERFD=0;HAVE_TIMINGSAFE_BCMP=0;HAVE_TM_GMTOFF=0;HAVE_TM_ZONE=0;HAVE_VASPRINTF=0;JS_NO_EXPORT=1;USE_64KB_PAGE_BLOCK=0;USE_ALLOW_LINE_AND_COLUMN_NUMBER_IN_BUILTINS=1;USE_AVIF=1;USE_BUN_EVENT_LOOP=1;USE_BUN_JSC_ADDITIONS=1;USE_BUN_JSC_ADDITIONS=1;USE_COMPRESSED_HEAP=0;USE_INSPECTOR_SOCKET_SERVER=1;USE_ISO_MALLOC=1;USE_JPEGXL=1;USE_LCMS=1;USE_LIBBACKTRACE=0;USE_MIMALLOC=0;USE_SKIA=0;USE_SKIA_ENCODERS=0;USE_SYSTEM_MALLOC=0;USE_SYSTEM_UNIFDEF=0;USE_TZONE_MALLOC=0;USE_UNIX_DOMAIN_SOCKETS=1;USE_WOFF2=1;WTF_DEFAULT_EVENT_LOOP=0"
)

# WTF library
add_library(JavaScriptCore::WTF STATIC IMPORTED)
set_target_properties(JavaScriptCore::WTF PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/WTF.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/WTF.lib"
)

# bmalloc library
add_library(JavaScriptCore::bmalloc STATIC IMPORTED)
set_target_properties(JavaScriptCore::bmalloc PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/bmalloc.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/bmalloc.lib"
)

# jsc library
add_library(JavaScriptCore::jsc STATIC IMPORTED)
set_target_properties(JavaScriptCore::jsc PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/jsc.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/jsc.lib"
)

# ICU data library
add_library(JavaScriptCore::icu-dt STATIC IMPORTED)
set_target_properties(JavaScriptCore::icu-dt PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/sicudt.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/sicudtd.lib"
)

# ICU i18n library
add_library(JavaScriptCore::icu-in STATIC IMPORTED)
set_target_properties(JavaScriptCore::icu-in PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/sicuin.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/sicuind.lib"
)

# ICU unicode library
add_library(JavaScriptCore::icu-uc STATIC IMPORTED)
set_target_properties(JavaScriptCore::icu-uc PROPERTIES
    IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/sicuuc.lib"
    IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/debug/lib/sicuucd.lib"
)
]=])
